DEPARTMENTS = {
	"Aesthetic and Interpretive Understanding":     "AESTH&INTP",
	"African and African American Studies":         "AFRAMER",
	"Akkadian":                                     "AKKAD",
	"American Civilization":                        "AM-CIV",
	"Ancient Near East":                            "ANE",
	"Anthropology":                                 "ANTHRO",
	"Applied Math":                                 "APMTH",
	"am":                                           "APMTH",
	"Applied Physics":                              "APPHY",
	"Arabic":                                       "ARABIC",
	"Aramaic":                                      "ARAMAIC",
	"Astronomy":                                    "ASTRON",
	"Biological and Biomedical Science":            "BBS",
	"Biological Chemistry & Molecular Pharmcology": "BCMP",
	"Biophysics":                                   "BIOPHYS",
	"Biostatistics":                                "BIOSTAT",
	"Biological Sciences in Public Health":         "BPH",
	"Biological Sciences in Dental Medicine":       "BSDM",
	"Catalan":                                      "CATALAN",
	"Cellular Biology":                             "CELLBIO",
	"Celtic":                                       "CELTIC",
	"Chemistry":                                    "CHEM",
	"Chemical Biology":                             "CHEMBIO",
	"Chinese":                                      "CHNSE",
	"Chinese History":                              "CHNSHIS",
	"Chinese Literature":                           "CHNSLIT",
	"Classical Hebrew":                             "CLAS-HEB",
	"Classical Studies":                            "CLAS-STDY",
	"Classical Archaeology":                        "CLASARCH",
	"Classical Philosophy":                         "CLASPHIL",
	"Classics":                                     "CLASSIC",
	"Comparative Literature":                       "COMPLIT",
	"Computer Science":                             "COMPSCI",
	# Common abbreviation
	'cs':                                           "COMPSCI", 
	"Chemical and Physical Biology":                "CPB",
	"Culture and Belief":                           "CULTR&BLF",
	"Drama":                                        "DRAMA",
	"Empirical and Mathematical Reasoning":         "E&M-REASON",
	"Earth and Planetary Sciences":                 "E-PSCI",
	"East Asian Buddhism":                          "EABS",
	"East Asian Studies":                           "EASTD",
	"Economics":                                    "ECON",
	# Common abbreviation
	"ec":                                           "ECON",
	"Egyptian":                                     "EGYPTIAN",
	"Engineering Sciences":                         "ENG-SCI",
	"English":                                      "ENGLISH",
	"Environmental Science and Public Policy":      "ESPP",
	"Ethical Reason":                               "ETH-REASON",
	"Expository Writing":                           "EXPOS",
	"Folklore and Mythology":                       "FOLKMYTH",
	"French":                                       "FRENCH",
	"Freshman Seminar":                             "FRSEMR",
	"Genetics":                                     "GENETIC",
	"German":                                       "GERMAN",
	"Global Health and Health Policy":              "GHHP",
	"Government":                                   "GOV",
	"Greek":                                        "GREEK",
	"History of Art and Architecture":              "HAA",
	"Human Biology And Translational Medicine":     "HBTM",
	"Human Evolutionary Biology":                   "HEB",
	"Hebrew":                                       "HEBREW",
	"History":                                      "HIST",
	"History of Literature":                        "HIST-LIT",
	"History of Science":                           "HISTSCI",
	"Health Policy":                                "HLTHPOL",
	"Historical Seminar Winthrop House":            "HSEMR-WI",
	"Immunology":                                   "IMUNOL",
	"Iranian":                                      "IRANIAN",
	"Irish":                                        "IRISH",
	"Islamic Civilization":                         "ISLAMCIV",
	"Italian":                                      "ITAL",
	"Japanese":                                     "JAPAN",
	"Japenese History":                             "JAPNHIST",
	"Japenese Literature":                          "JAPNLIT",
	"Jewish History":                               "JEWISHST",
	"Korean":                                       "KOREAN",
	"Korean History":                               "KORHIST",
	"Korean Literature":                            "KORLIT",
	"Latin American Studies":                       "LAT-STD",
	"Latin":                                        "LATIN",
	"Life Science":                                 "LIFESCI",
	# Common abbreviation
	"ls":                                           "LIFESCI",
	"Linguistics":                                  "LING",
	"Literature":                                   "LITER",
	"Life and Physical Sciences":                   "LPS",
	"Manchu":                                       "MANCHU",
	"Mathematics":                                  "MATH",
	"Mind  Brain  and Behavior":                    "MBB",
	"Molecular and Cellular Biology":               "MCB",
	"Medical Sciences":                             "MED-SCI",
	"Medieval Greek":                               "MEDGREEK",
	"Medieval Latin":                               "MEDLATIN",
	"Medieval Studies":                             "MEDVLSTD",
	"Microbiology":                                 "MICROBI",
	"Modern Hebrew":                                "MOD-HEB",
	"Modern Greek":                                 "MODGRK",
	"Music":                                        "MUSIC",
	"Near Eastern Languages and Civilizations":     "NEC",
	"Nepali":                                       "NEP",
	"Neurobiology":                                 "NEUROBIO",
	# Common abbreviation
	"neuro":                                        "NEUROBIO",	
	"Organismic and Evolutionary Biology":          "OEB",
	"Pathology":                                    "PATHOL",
	"Persian":                                      "PERSIAN",
	"Philosophy":                                   "PHIL",
	"Physics":                                      "PHYSCI",
	"Physics":                                      "PHYSICS",
	"Portuguese":                                   "PORTUG",
	"Psychology":                                   "PSY",
	"Religion":                                     "RELIGION",
	"Romance Language Studies":                     "ROM-STD",
	"Sanskrit":                                     "SANSKRIT",
	"South Asian Studies":                          "SAS",
	"Scandinavian":                                 "SCAND",
	"Science of Living Systems":                    "SCI-LIVSYS",
	# Common abbreviation
	"sls":                                          "SCI-LIVSYS",
	"Science of the Physical Universe":             "SCI-PHYUNV",
	"Scottish Gaelic":                              "SCOTGAELIC",
	"Stem Cell and Regenerative Biology":           "SCRB",
	"Semitic Philology":                            "SEMPHIL",
	"Slavic":                                       "SLAVIC",
	"Social Studies":                               "SOC-STD",
	"Societies of the World":                       "SOC-WORLD",
	"Sociology":                                    "SOCIOL",
	"Spanish":                                      "SPANSH",
	"Statistics":                                   "STAT",
	"Swahili":                                      "SWAHILI",
	"Swedish":                                      "SWEDISH",
	"Systems Biology":                              "SYSTBIO",
	"Tamil":                                        "TAM",
	"Thai":                                         "THI",
	"Tibetan":                                      "TIBET",
	"Turkish":                                      "TURKISH",
	"Twi":                                          "TWI",
	"Ukrainian":                                    "UKRAN",
	"Urdu-Hindi":                                   "URD",
	"United States in the World":                   "US-WORLD",
	"Uyghur":                                       "UYGHUR",
	"Visual and Enviromental Studies":              "VES",
	"Vietnamese":                                   "VIETNAM",
	"Virology":                                     "VIROLOGY",
	"Welsh":                                        "WELSH",
	"Women and Gender Studies":                     "WOMGEN",
	"Yiddish":                                      "YIDDISH",
	"Yoruba":                                       "YORUBA"
}





